@host=https://localhost:5555

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Le",
    "lastName": "Hoang",
    "email": "hoangxam2@gmail.com",
    "password": "hoanglee217",
    "phoneNumber": "0901968477",
}
 